FROM rockylinux:8

WORKDIR /app

# 必要なパッケージのインストール
RUN dnf install -y \
    python39 \
    python39-pip \
    python39-devel \
    gcc \
    mysql-devel \
    git \
    libffi-devel \
    openssl-devel \
    systemd && \
    dnf clean all

# Pythonの依存関係をインストール
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# アプリケーションコードをコピー
COPY . .

# ポート公開
EXPOSE 8000

# systemdで起動（コンテナを永続化）
CMD ["/sbin/init"]